#!/bin/sh
# Load in modules
module reset
module load mkl
module load linaro-forge
ml

make-profiler-libraries --platform=cray --lib-type=shared
mpicc -L$(pwd) -lmap-sampler-pmpi -lmap-sampler -Wl,--eh-frame-hdr -Wl,-rpath=$(pwd) -o cfd.exe miniapp.exe build/*.o
# Compile
make profile

# Creating executable
cd test/

cat > EXEC_STEP << EXEC
#!/bin/bash
#PBS -A UCSG0002
#PBS -N hybrid_job
#PBS -q tutorial 
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=32:mpiprocs=32
#PBS -j oe

module reset
module load mkl
module load linaro-forge

map --connect mpiexec ./miniapp.exe
EXEC

# Run application
qsub < EXEC_STEP

