#!/bin/sh
# Load in modules
module reset
module load mkl
ml
# Compile
make profile

# Creating executable
cd test/

cat > EXEC_STEP << EXEC
#!/bin/bash
#PBS -A UCSG0002
#PBS -N hybrid_job
#PBS -q main 
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=32:mpiprocs=32
#PBS -o exec.out
#PBS -e exec.err

module reset
module load mkl

mpiexec ./miniapp.exe > output.out
EXEC

# Run application
qsub < EXEC_STEP

