#!/bin/sh
# Load in modules
module load ncarenv
module reset
module load mkl
module load nvhpc
module load cray-mpich
ml

# Compile
nvfortran -g -O2 -acc -fast -c src/miniapp_rkc.f90
nvfortran -g -O2 -acc -fast -c src/chemistry.f90
nvfortran -g -O2 -acc -fast -c src/chem_ode_miniapp.f90
nvfortran -r8 -acc=multicore -Minfo=ftn,all -module ./build -g -O2
# Creating executable
cd test/

cat > EXEC_STEP << EXEC
#!/bin/bash
#PBS -A UCSG0002
#PBS -N hybrid_job
#PBS -q tutorial 
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=32:mpiprocs=32:ngpus=1:mem=16GB
#PBS -j oe
#PBS -l gpu_type=a100


module load ncarenv
module reset
module load mkl
module load nvhpc
module load cray-mpich

mpiexec ./miniapp.exe > output.out
EXEC

# Run application
# qsub < EXEC_STEP

