#!/bin/sh
# Load in modules
module reset
module load mkl
module load nvhpc
module load openmpi
ml

# Compile
mpif90 -acc -gpu=cc80 -Minfo=accel -c src/chem_ode_miniapp.f90 -o build/chem_ode_miniapp.o
# Creating executable
cd test/

cat > EXEC_STEP << EXEC
#!/bin/bash
#PBS -A UCSG0002
#PBS -N hybrid_job
#PBS -q tutorial 
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=32:mpiprocs=32:ngpus=1:mem=16GB
#PBS -j oe
#PBS -l gpu_type=a100

module reset
module load mkl
module load nvhpc
module load openmpi

mpiexec ./miniapp.exe > output.out
EXEC

# Run application
qsub < EXEC_STEP

